apiVersion: "v1"
kind: "Secret"
metadata:
  name: rasa-tls-secret
  namespace: rasax
type: "Opaque"
stringData:
  fullchain.pem: $(cat ../certificates/fullchain.pem.b64 | base64)
  privkey.pem: $(cat ../certificates/privkey.pem.b64 | base64)
